services:
   db:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASS}
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT}
    ports:
      - 3306:3306
    volumes:
      - /Users/hamed/mysql:/var/lib/mysql
