services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASS}
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: springboot-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mydb
      - SPRING_DATASOURCE_USERNAME=${SQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${SQL_PASS}
    ports:
      - 8080:8080

volumes:
  mysql_data:
