name: Build and Deploy Docker Image to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push Docker image
        run: |
          docker build -t milkchequeregistry.azurecr.io/milkcheque:latest .
          docker push milkchequeregistry.azurecr.io/milkcheque:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MilkChequeWebApp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'milkchequeregistry.azurecr.io/milkcheque:latest'
